apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-fixed
  namespace: 25rp19452-niyonkuru
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'helpdesk-monitor'
        environment: 'production'
        service: '25RP19452-NIYONKURU'

    rule_files:
      - '/etc/prometheus/rules/alerts.yml'

    scrape_configs:
      - job_name: 'helpdesk-app'
        static_configs:
          - targets: ['helpdesk-service-headless:5000']
        metrics_path: '/metrics'
        scrape_interval: 10s

      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
