apiVersion: v1
kind: ServiceAccount
metadata:
  name: helpdesk-sa
  namespace: 25rp19452-niyonkuru
  labels:
    app: helpdesk

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helpdesk-role
  namespace: 25rp19452-niyonkuru
rules:
- apiGroups: [""]
  resources: ["pods", "pods/logs"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helpdesk-rolebinding
  namespace: 25rp19452-niyonkuru
subjects:
- kind: ServiceAccount
  name: helpdesk-sa
  namespace: 25rp19452-niyonkuru
roleRef:
  kind: Role
  name: helpdesk-role
  apiGroup: rbac.authorization.k8s.io
