apiVersion: v1
kind: Service
metadata:
  name: helpdesk-service
  namespace: 25rp19452-niyonkuru
  labels:
    app: helpdesk
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: helpdesk
    tier: backend
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  sessionAffinity: None
  externalTrafficPolicy: Local

---
apiVersion: v1
kind: Service
metadata:
  name: helpdesk-service-headless
  namespace: 25rp19452-niyonkuru
  labels:
    app: helpdesk
spec:
  clusterIP: None
  selector:
    app: helpdesk
  ports:
  - name: http
    port: 5000
    targetPort: 5000
