apiVersion: v1
kind: PersistentVolume
metadata:
  name: helpdesk-pv
  namespace: 25rp19452-niyonkuru
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/helpdesk"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helpdesk-pvc
  namespace: 25rp19452-niyonkuru
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: helpdesk-pv
